/**
 * Compile sections.jsx + app.jsx → sections.js + app.js
 *
 * The .jsx source files use globals: React, ReactDOM (loaded via UMD <script> tags
 * in index.html). So we don't bundle — we just transform JSX → React.createElement
 * and minify. Output is plain JS that can be loaded via a regular <script> tag,
 * removing the need to ship Babel-standalone (~3 MB) to every visitor.
 *
 * Run with: npm run compile
 * Commit the resulting .js files to the repo.
 */
import { buildSync } from "esbuild";
import { writeFileSync } from "node:fs";

const sources = ["sections.jsx", "app.jsx"];

for (const src of sources) {
  const result = buildSync({
    entryPoints: [src],
    bundle: false,
    loader: { ".jsx": "jsx" },
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    minify: true,
    target: ["es2020", "chrome90", "safari14", "firefox90"],
    write: false,
    legalComments: "none",
  });
  const out = src.replace(/\.jsx$/, ".js");
  const banner = `/* Compiled from ${src}. Edit the .jsx source — DO NOT EDIT THIS FILE. */\n`;
  writeFileSync(out, banner + result.outputFiles[0].text);
  const kb = (result.outputFiles[0].text.length / 1024).toFixed(1);
  console.log(`  ✓ ${src} → ${out}  (${kb} KB minified)`);
}
console.log("Done. Commit the .js files alongside the .jsx sources.");
